from . import user
from . import driver
from . import vehicle
from . import shipment
from . import trip
from . import gps_tracking
from . import maintenance
from . import fuel_record
from . import notification
from . import attendance
from . import email_otp
from . import leave_request
from . import shipment_history
from . import activity_log
from . import job_run
