"""initial schema

Revision ID: f1f98b5c50df
Revises: 
Create Date: 2026-07-25 20:38:12.521477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f98b5c50df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Users must be created before the dependent driver and notification
    # tables.  The original autogenerated revision omitted this table.
    op.create_table('users',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=15), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=False, server_default='Driver'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('email', name='users_email_key')
    )

    op.create_table('vehicles',
        sa.Column('vehicle_id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('vehicle_id')
    )

    op.create_table('drivers',
        sa.Column('driver_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('driver_id'),
        sa.UniqueConstraint('user_id')
    )

    op.create_table('fuel_records',
        sa.Column('fuel_id', sa.UUID(), nullable=False),
        sa.Column('vehicle_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id']),
        sa.PrimaryKeyConstraint('fuel_id')
    )

    op.create_table('gps_tracking',
        sa.Column('tracking_id', sa.UUID(), nullable=False),
        sa.Column('vehicle_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id']),
        sa.PrimaryKeyConstraint('tracking_id')
    )

    op.create_table('notifications',
        sa.Column('notification_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('notification_id')
    )

    op.create_table('vehicle_maintenance',
        sa.Column('maintenance_id', sa.UUID(), nullable=False),
        sa.Column('vehicle_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id']),
        sa.PrimaryKeyConstraint('maintenance_id')
    )

    op.create_table('attendance',
        sa.Column('attendance_id', sa.UUID(), nullable=False),
        sa.Column('driver_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id']),
        sa.PrimaryKeyConstraint('attendance_id')
    )

    op.create_table('shipments',
        sa.Column('shipment_id', sa.UUID(), nullable=False),
        sa.Column('vehicle_id', sa.UUID(), nullable=True),
        sa.Column('driver_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id']),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id']),
        sa.PrimaryKeyConstraint('shipment_id')
    )

    op.create_table('trips',
        sa.Column('trip_id', sa.UUID(), nullable=False),
        sa.Column('vehicle_id', sa.UUID(), nullable=True),
        sa.Column('driver_id', sa.UUID(), nullable=True),
        sa.Column('shipment_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id']),
       sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id']),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id']),
        sa.PrimaryKeyConstraint('trip_id')
    )

    # Create PostgreSQL ENUM type before altering users.role
    role_enum = sa.Enum(
        'Admin',
        'FleetManager',
        'Driver',
        'Dispatcher',
        name='roleenum'
    )

    role_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        """
        ALTER TABLE users
        ALTER COLUMN role DROP DEFAULT,
        ALTER COLUMN role TYPE roleenum
        USING role::roleenum
        """
    )
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'Driver'::roleenum")

    op.drop_constraint(
        op.f('users_email_key'),
        'users',
        type_='unique'
    )

    op.create_index(
        op.f('ix_users_email'),
        'users',
        ['email'],
        unique=True
    )

    # ### end Alembic commands ###
