import { useEffect, useState } from "react";
import api from "../api/axios";
import { useAuth } from "../context/AuthContext";

export default function LeaveRequests() {
  const { user } = useAuth(); const [items, setItems] = useState([]); const [leave_date, setDate] = useState(""); const [reason, setReason] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setItems((await api.get("/leave-requests/")).data); } catch (e) { setError(e.response?.data?.detail || "Unable to load leave requests."); } };
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, []);
  const isDriver = user?.role === "Driver";
  return <div className="p-8"><h1 className="text-3xl font-bold mb-2">Leave Requests</h1><p className="text-gray-600 mb-6">{isDriver ? "Request leave for a particular date and track the manager's decision." : "Approve or reject driver leave requests."}</p>{error && <p className="text-red-600 mb-3">{error}</p>}{isDriver && <form onSubmit={async e => { e.preventDefault(); try { await api.post("/leave-requests/", { leave_date, reason: reason || null }); setDate(""); setReason(""); await load(); } catch (x) { setError(x.response?.data?.detail || "Unable to submit leave request."); } }} className="bg-white shadow rounded p-5 flex gap-3 mb-6"><input required type="date" value={leave_date} onChange={e => setDate(e.target.value)} className="border rounded p-2"/><input placeholder="Reason (optional)" value={reason} onChange={e => setReason(e.target.value)} className="border rounded p-2 flex-1"/><button className="bg-blue-600 text-white rounded px-4">Request Leave</button></form>}<table className="w-full border"><thead className="bg-gray-100"><tr><th className="p-3">Date</th>{!isDriver && <th>Driver ID</th>}<th>Reason</th><th>Status</th>{!isDriver && <th>Decision</th>}</tr></thead><tbody>{items.map(item => <tr className="border-t text-center" key={item.leave_id}><td className="p-3">{item.leave_date}</td>{!isDriver && <td>{item.driver_id}</td>}<td>{item.reason || "—"}</td><td>{item.status}</td>{!isDriver && <td>{item.status === "Pending" && <><button onClick={async () => { await api.patch(`/leave-requests/${item.leave_id}`, { status: "Approved" }); await load(); }} className="bg-green-600 text-white px-3 py-1 rounded mr-2">Accept</button><button onClick={async () => { await api.patch(`/leave-requests/${item.leave_id}`, { status: "Rejected" }); await load(); }} className="bg-red-600 text-white px-3 py-1 rounded">Reject</button></>}</td>}</tr>)}{!items.length && <tr><td colSpan="5" className="p-5 text-center">No leave requests.</td></tr>}</tbody></table></div>;
}
